version: "3.4"
services:
  postgres_db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "grocerydeliveryservicedb"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
  grocerydeliveryapi:
    image: grocerydeliveryapi:latest
    ports:
      - "5000:80"
    depends_on:
      - "postgres_db"
    build:
      context: grocery-delivery-api
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"